### ISSUE TITLE
Search comes up blank

### ISSUE THREAD

**Issue by aporzio1** [Xoconoch/zotifarrr#3]
looks like its returning error 500 but I don't see any other errors 

```
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:7070
 * Running on http://172.31.0.2:7070
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: ***-***-***
192.168.1.249 - - [24/Jan/2025 22:36:24] "GET / HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 22:36:24] "GET /css/main.css HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 22:36:24] "GET /js/app.js HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 22:36:24] "GET /js/components/load.js HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 22:36:24] "GET /js/components/search.js HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 22:36:24] "GET /js/components/download.js HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 22:36:24] "GET /api/check HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 22:36:24] "GET /favicon.ico HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 23:04:18] "GET / HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 23:04:18] "GET /css/main.css HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:04:18] "GET /js/app.js HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:04:18] "GET /js/components/load.js HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:04:18] "GET /js/components/search.js HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:04:18] "GET /js/components/download.js HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:04:19] "GET /api/check HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 23:05:28] "GET / HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 23:05:28] "GET /css/main.css HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:05:28] "GET /js/app.js HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:05:28] "GET /js/components/load.js HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:05:28] "GET /js/components/search.js HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:05:28] "GET /js/components/download.js HTTP/1.1" 304 -
192.168.1.249 - - [24/Jan/2025 23:05:28] "GET /api/check HTTP/1.1" 200 -
192.168.1.249 - - [24/Jan/2025 23:05:35] "GET /api/search?account=aporzio1&query=beast HTTP/1.1" 500 -
192.168.1.249 - - [24/Jan/2025 23:05:37] "GET /api/search?account=aporzio1&query=beast HTTP/1.1" 500 -
192.168.1.249 - - [24/Jan/2025 23:23:14] "GET /api/search?account=aporzio1&query=test HTTP/1.1" 500 -
```

**Comment by Xoconoch** [comment]
Could you provide the output of `docker exec -it [zotifarr container name] python3 -m zotify --credentials-location ./credentials/aporzio1/credentials.json -s test`?

**Comment by StarTerrarium** [comment]
I had this problem and resolved it (although download still isn't working exactly how I expect).   This was the log output from the above:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/.config/zotify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/zotify/__main__.py", line 68, in <module>
    main()
  File "/app/zotify/__main__.py", line 64, in main
    args.func(args)
  File "/app/zotify/app.py", line 23, in client
    Zotify(args)
  File "/app/zotify/zotify.py", line 20, in __init__
    Zotify.CONFIG.load(args)
  File "/app/zotify/config.py", line 101, in load
    Path(PurePath(true_config_file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.11/pathlib.py", line 1120, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.config'
```

Note the weird path Zotify is looking in for a config file:  `/.config`..  From the root.  Looking at the Zotify docs it should be looking for `/home/<username>/.config`

This might have something to do with my forcing the container to run under a specific user & group ID, so the process running in it doesn't have any associated user in the container.  Like getting a `docker exec -it zotifarrr whoami` just shows `whoami: cannot find name for user ID 1000`

So that's my best guess at the root cause.

I fixed this by just creating an empty directory and mounting it to `/.config` in the container.  Probably not the most correct solution, but it's working. 

The relevant section from my docker-compose for reference. 
```yml
  zotifarrr:
    # Built locally.  See https://github.com/Xoconoch/zotifarrr
    image: zotifarrr
    container_name: zotifarrr
    restart: unless-stopped
    user: ${UID}:${GID}
    environment:
      - TZ=${TZ}
    volumes:
      - /speed/app-config/zotifarrr/credentials:/app/credentials
      - /speed/app-config/zotifarrr/zotify-config:/.config
      - /bulk/data/media/music:/app/downloads/music
    labels:
      - traefik.enable=true
      - traefik.http.routers.zotifarrr.rule=Host(`zotifarrr.${DOMAIN}`)
      - traefik.http.routers.zotifarrr.entrypoints=websecure-internal
      - traefik.http.routers.zotifarrr.tls.certresolver=cloudflare-dns
```

Now my problem is that I can search for things, click download.  It says they downloaded correctly..  But I have no idea where on the file system they hvae gone.  I was expecting it to download to `/app/downloads/music`  but it isn't.

**Comment by Xoconoch** [comment]
Yeah you probably built the image with a flawed Dockerfile that was up for a while, my bad! It was lacking ffmpeg so it inevitably fails every download, just remove the current image, rebuild it using the current Dockerfile and it should work. Apologies for that rookie mistake.

**Comment by StarTerrarium** [comment]
Resolved that problem too - similar root cause.  In the Zotify codebase it just fetching the users home directory for a few things.  eg:
```
            system_paths = {
                'win32': Path.home() / 'AppData/Roaming/Zotify',
                'linux': Path.home() / '.local/share/zotify',
                'darwin': Path.home() / 'Library/Application Support/Zotify'
            }
```
And in this situation where I've specified a specific UID to run under (1000), and there is no matching user in the container, I'm guessing this gets into murky waters, may result in an empty string, which means it will create a path from the root `/.local/share/zotify`.

So my hacky workaround from above.. Creating an empty dir, mounting it to `/.local` worked to get past this, and actually get things to download.

But this is all hacky workaround.  I'll have a look for a better way.

**Comment by StarTerrarium** [comment]
It's late and I'm tired, but here is what I have for now.  Added `gosu` as a dependency in the `Dockerfile`.  Then updated `entrypoint.sh` to be aware of optional `PUID` and `PGID` environment variables (similar to linuxserver.io images).  Then it creates a user & group for that UID & GID.

Finally it executes `python` under that user.

So the docker-compose.yml:

```yml
  zotifarrr:
    # Built locally.  See https://github.com/Xoconoch/zotifarrr
    image: zotifarrr:latest
    container_name: zotifarrr
    restart: unless-stopped
    environment:
      - PUID=${UID}
      - PGID=${GID}
      - TZ=${TZ}
    volumes:
      - /speed/app-config/zotifarrr/credentials:/app/credentials
      - /speed/app-config/zotifarrr/test-data:/app/downloads/music
    labels:
      - traefik.enable=true
      - traefik.http.routers.zotifarrr.rule=Host(`zotifarrr.${DOMAIN}`)
      - traefik.http.routers.zotifarrr.entrypoints=websecure-internal
      - traefik.http.routers.zotifarrr.tls.certresolver=cloudflare-dns
```

Dockerfile (also moved the pip install earlier so it wouldn't re-downloaded on almost any change):
```

FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg gosu && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt --timeout 150
COPY ./app.py ./
COPY ./utils ./utils
COPY ./frontend ./frontend
COPY ./routes ./routes
COPY ./zotify ./zotify

COPY ./entrypoint.sh ./
RUN chmod +x ./entrypoint.sh


EXPOSE 7070

RUN mkdir ./credentials
RUN mkdir ./downloads

CMD ["./entrypoint.sh"]
```

And the entrypoint script:
```
#!/bin/sh
set -e

USERNAME="zotifarrr"
GROUP="zotifarrr"
HOME="/home/$USERNAME"

# Handle for custom user & group configurations.
USER_ID=${PUID:-1000}
GROUP_ID=${PGID:-1000}

# Create the group if it doesn't exist
if ! getent group "$GROUP" > /dev/null; then
    echo "Creating group $GROUP with ID $GROUP_ID"
    groupadd -g "$GROUP_ID" "$GROUP"
fi

# Create the user if it doesn't exist
if ! id "$USERNAME" > /dev/null 2>&1; then
    echo "Creating user $USERNAME with ID $USER_ID"
    useradd -u "$USER_ID" -g "$GROUP_ID" -m -d "$HOME" "$USERNAME"
fi

# Ensure the home directory exists and is owned by the user
mkdir -p "$HOME"
chown -R "$USER_ID":"$GROUP_ID" "$HOME"

# Export HOME environment variable
echo "Setting HOME directory as $HOME"
export HOME="$HOME"

# Switch to the user and execute the given command
echo "Starting application with UID:GID of $USER_ID:$GROUP_ID..."
exec gosu "$USER_ID":"$GROUP_ID" "python" "/app/app.py"
```

All seems to be working flawlessly for me now.  Still not sure if this is a 'good' way of solving my problem or if it's the root cause of the original issue reporter though.
